// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DeveloperTest.Database;

namespace DeveloperTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeveloperTest.Database.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Engineer")
                        .HasColumnType("nvarchar(max)");
                    
                    b.Property<string>("CustomerId")
                        .ValueGeneratedNever()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime2");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            Engineer = "Test",
                            When = new DateTime(2020, 2, 19, 14, 14, 16, 317, DateTimeKind.Local).AddTicks(2552)
                        });
                });
            modelBuilder.Entity("DeveloperTest.Database.Models.CustomerType", b =>
            {
                b.Property<int>("CustomerTypeId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CustomerTypeId");

                b.ToTable("CustomerTypes");

                b.HasData(
                    new
                    {
                        CustomerTypeId = 1,
                        Description = "Large"
                    });
                b.HasData(
                    new
                    {
                        CustomerTypeId = 2,
                        Description = "Small"
                    });
            });
            modelBuilder.Entity("DeveloperTest.Database.Models.Customer", b =>
            {
                b.Property<int>("CustomerId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                
                b.Property<String>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("CustomerTypeId")
                    .HasColumnType("int");

                b.HasKey("CustomerId");

                b.ToTable("Customers");

                b.HasData(
                    new
                    {
                        JobId = 1,
                        Name = "Sam Lad",
                        CustomerTypeId = 1
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
